name: "Mdns reflector for Matter"
description: "Mdns between wlan0 and enu1"
version: "1.0.5"
slug: "reflector"
boot: auto
init: false
usb: true
udev: true
host_network: true

privileged:
  - NET_ADMIN
  - NET_RAW

arch:
  - aarch64
